export enum Language {
  arabic = 'ar',
  chinese = 'zh',
  english = 'en',
  french = 'fr',
  german = 'de',
  indonesian = 'id',
  italian = 'it',
  japanese = 'ja',
  korean = 'ko',
  portuguese = 'pt',
  russian = 'ru',
  spanish = 'es',
  turkish = 'tr',
  unknown = 'unknown',
}
